name: Publish Docker image to GHCR on a new version

on:
  push:
    branches:
      - main
      - dockertest
#    tags: 
#      - [0-9]+.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test_quality:
    uses: ./.github/workflows/quality.yml 
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ghcr.io
        run: echo "${{ secrets.GHCR_PAT }}" | docker login --username ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
      - name: Build and tag image
        run: docker build . -t ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:latest
      - name: Push image to ghcr.io
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

